class Commute < ApplicationRecord

  # Cost calculations are hard-coded into the method, see method below. To find the most recent IRS Standard Mileage Rate for Business, go to https://www.irs.gov/uac/newsroom/2016-standard-mileage-rates-for-business-medical-and-moving-announcedIRS.
  # Transit comparative cost is hard-coded into the method, see method below. To calculate new data, go to https://www.transit.dot.gov/ntd and download the latest NTD Data/NTD Data Reports

  # points are defined as polylines along the route generated by Google Maps, each point has it's own latitude and longitude
  has_many    :points, dependent: :destroy

  # origin is the origin address for the traveler (home), destination is the work address.
  # Addresses cannot be any further than 65 miles from the center of Indianapolis (latitude and longitude calculated by Google Maps)
  validates   :origin, presence: true
  validates   :destination, presence: true
  validate    :origin_cannot_be_outside_indianapolis,
              :destination_cannot_be_outside_indianapolis, on: :create

  before_save :save_distance_per_day,
              :save_distance_per_week,
              :save_drive_minutes_per_week,
              :save_drive_hours_per_week,
              :save_drive_days_per_year,
              :save_drive_cost_per_week,
              :save_drive_cost_per_year

# see Geokit-rails gem for details on acts_as_mappable
  acts_as_mappable :auto_geocode=>{:field=>:origin, :error_message=>'Could not geocode address'}

# validates that origin address is no further than 65 miles from the center of Indianapolis
  def origin_cannot_be_outside_indianapolis
    indy_location = Geokit::Geocoders::GoogleGeocoder.geocode('Indianapolis, IN')
    origin_location = Geokit::Geocoders::GoogleGeocoder.geocode(self.origin)
    if indy_location.distance_to(origin_location) > 65
      errors.add(:origin, "Origin cannot be more than 65 miles outside of Indianapolis")
    end
  end

# validates that destination address is no further than 65 miles from the center of Indianapolis
  def destination_cannot_be_outside_indianapolis
    indy_location = Geokit::Geocoders::GoogleGeocoder.geocode('Indianapolis, IN')
    destination_location = Geokit::Geocoders::GoogleGeocoder.geocode(self.destination)
    if indy_location.distance_to(destination_location) > 65
      errors.add(:destination, "Destination cannot be more than 65 miles outside of Indianapolis")
    end
  end

# round trip miles traveled
  def save_distance_per_day
    self.distance_per_day = distance_in_miles * 2
  end

# total miles traveled in a 5 day period
  def save_distance_per_week
    self.distance_per_week = distance_per_day * 5
  end

# geokit method, calculated for 10 one-way commutes
  def save_drive_minutes_per_week
    self.drive_minutes_per_week = drive_time_in_minutes * 10
  end

# time driven converted into hours
  def save_drive_hours_per_week
    self.drive_hours_per_week = (drive_minutes_per_week / 60.0).round(2)
  end

# time driven into days given 50 work-weeks
  def save_drive_days_per_year
    self.drive_days_per_year = ((drive_hours_per_week * 50) / 24.0).round(2)
  end

# Cost calculations based on IRS Standard Mileage Rate for Business, hard-coded
  def irs_standard_mileage_rate
    0.54
  end

  def save_drive_cost_per_week
    self.drive_cost_per_week = (distance_per_week * irs_standard_mileage_rate).round
  end

  def save_drive_cost_per_year
    self.drive_cost_per_year = (drive_cost_per_week * 50).round
  end

# Geokit-rails calculation, using a 5 mile radius based on the origin address
  def number_of_closest_commuters
    Commute.within(5, :origin => self.origin).count
  end

  def average_distance_traveled_of_closest_commuters
    Commute.within(5, :origin => self.origin).average(:distance_in_miles).round.to_s
  end

# NTD Transit Data calculation, hard-coded NTD Transit Data for average US Transit Cost
  def national_average_transit_cost
    (2.342876994).round(2)
  end

  def transit_cost_per_week
    (national_average_transit_cost * 10).round
  end

  def transit_cost_per_year
    (transit_cost_per_week * 50).round
  end

  def savings_transit_cost_per_week
    self.drive_cost_per_week - transit_cost_per_week
  end

  def savings_transit_cost_per_year
    self.drive_cost_per_year - transit_cost_per_year
  end

end
